"""Generate clef_unicode.inc: the Unicode tables the native tokenizer needs.

  - \\p{L}, \\p{N} ranges for the Qwen pre-tokenizer regex (general categories L*, N*).
  - \\s ranges (the Unicode White_Space property, which is what Oniguruma's \\s uses).
  - NFC data: canonical combining classes, single-level canonical decompositions, and
    primary composites. A two-code-point canonical decomposition is a primary composite
    exactly when NFC maps it back to the original character; deriving it that way
    applies the composition-exclusion and non-starter rules without a separate table.

Source: Python's unicodedata (version printed into the header). Hangul syllables are
algorithmic and handled in C.
"""

from __future__ import annotations

import sys
import unicodedata

MAX_CP = 0x110000
HANGUL = range(0xAC00, 0xD7A4)

# Unicode White_Space (PropList.txt). Python's str.isspace() is not this property
# (it adds U+001C..U+001F), so it is spelled out.
WHITE_SPACE = [
    (0x0009, 0x000D), (0x0020, 0x0020), (0x0085, 0x0085), (0x00A0, 0x00A0),
    (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F),
    (0x205F, 0x205F), (0x3000, 0x3000),
]


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(MAX_CP + 1):
        hit = cp < MAX_CP and pred(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def emit_ranges(name: str, rs: list[tuple[int, int]]) -> str:
    body = ",\n".join(
        "    " + ", ".join(f"{{0x{lo:05x}, 0x{hi:05x}}}" for lo, hi in rs[i:i + 4])
        for i in range(0, len(rs), 4)
    )
    return f"static const clef_urange {name}[] = {{\n{body}\n}};\n"


def main() -> None:
    cat = lambda cp: unicodedata.category(chr(cp))  # noqa: E731
    letters = ranges(lambda cp: cat(cp).startswith("L"))
    numbers = ranges(lambda cp: cat(cp).startswith("N"))

    ccc_ranges: list[tuple[int, int, int]] = []
    for cp in range(MAX_CP):
        c = unicodedata.combining(chr(cp))
        if not c:
            continue
        if ccc_ranges and ccc_ranges[-1][1] == cp - 1 and ccc_ranges[-1][2] == c:
            ccc_ranges[-1] = (ccc_ranges[-1][0], cp, c)
        else:
            ccc_ranges.append((cp, cp, c))

    decomp: list[tuple[int, int, int]] = []
    comp: list[tuple[int, int, int]] = []
    for cp in range(MAX_CP):
        if cp in HANGUL:
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue  # no mapping, or a compatibility mapping (NFC ignores those)
        parts = [int(x, 16) for x in d.split()]
        if len(parts) > 2:
            raise SystemExit(f"U+{cp:04X}: canonical decomposition longer than 2")
        decomp.append((cp, parts[0], parts[1] if len(parts) == 2 else 0))
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            comp.append((parts[0], parts[1], cp))
    comp.sort()

    out = [
        f"/* Generated by tools/gen_unicode.py from Python {sys.version.split()[0]} unicodedata "
        f"{unicodedata.unidata_version}. Do not edit. */\n",
        "typedef struct { uint32_t lo, hi; } clef_urange;\n",
        "typedef struct { uint32_t lo, hi; uint8_t ccc; } clef_ccc_range;\n",
        "typedef struct { uint32_t cp, a, b; } clef_decomp_entry;\n",
        "typedef struct { uint32_t a, b, cp; } clef_comp_entry;\n\n",
        emit_ranges("clef_letter_ranges", letters),
        emit_ranges("clef_number_ranges", numbers),
        emit_ranges("clef_space_ranges", WHITE_SPACE),
        "static const clef_ccc_range clef_ccc_ranges[] = {\n"
        + ",\n".join(f"    {{0x{lo:05x}, 0x{hi:05x}, {c}}}" for lo, hi, c in ccc_ranges) + "\n};\n",
        "static const clef_decomp_entry clef_decomp[] = {\n"
        + ",\n".join(f"    {{0x{cp:05x}, 0x{a:05x}, 0x{b:05x}}}" for cp, a, b in decomp) + "\n};\n",
        "static const clef_comp_entry clef_comp[] = {\n"
        + ",\n".join(f"    {{0x{a:05x}, 0x{b:05x}, 0x{cp:05x}}}" for a, b, cp in comp) + "\n};\n",
    ]
    sys.stdout.write("".join(out))
    print(
        f"letters={len(letters)} numbers={len(numbers)} ccc={len(ccc_ranges)} "
        f"decomp={len(decomp)} comp={len(comp)}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
